### PR TITLE
Browser support and additional tests

### PR DESCRIPTION
**Pull request by rowanv**
Added support for Chrome, Edge, and Safari with accompanying unit tests. Increased coverage by adding additional unit tests for timeout errors and invalid throughput inputs. Added additional tests that check introduction of non-numeric metrics separately.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/14)

### CODE REVIEW

**Comment by mtlynch** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_html5_driver.py, line 372 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/14#-KEW6HKTG31y_Q_hlWz8:-KEW6HKTG31y_Q_hlWz9:-533372176) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9a8b7048fbd4a755f335531544822ef6e92fd72c/tests/test_html5_driver.py#L372)):*
Can we use standard `with` context handler here to avoid `start()`/`stop()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/14#-:-KEW6sEflSZyUBSUlm-q:1417088721)*

**Comment by rowanv** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_html5_driver.py, line 372 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/14#-KEW6HKTG31y_Q_hlWz8:-KEWEaEnZOyo8PjxrDLo:1111535654) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9a8b7048fbd4a755f335531544822ef6e92fd72c/tests/test_html5_driver.py#L372)):*
Thanks. Would that be preferable even though we'd then have nested `with` statements with double indentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/14)*

**Comment by mtlynch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_html5_driver.py, line 372 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/14#-KEW6HKTG31y_Q_hlWz8:-KEWFUydOSrbdo8leQOY:5652724) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9a8b7048fbd4a755f335531544822ef6e92fd72c/tests/test_html5_driver.py#L372)):*
Yeah, nested `with`s are not ideal, but we never want the developer to have to manually manage something that a context handler could manage automatically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/14)*

**Comment by rowanv** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_html5_driver.py, line 372 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/14#-KEW6HKTG31y_Q_hlWz8:-KEX3kKgbucdNaXNUdVw:-1962606219) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9a8b7048fbd4a755f335531544822ef6e92fd72c/tests/test_html5_driver.py#L372)):*
Sounds good, fixed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/14)*

**Pull request merged**
