### PR TITLE
Adding script for Selenium extension prerequisites

### PR DESCRIPTION
**Pull request by rowanv**
Installs necessary files for running the NDT test with various additional browsers.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/15)

### CODE REVIEW

**Comment by mtlynch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[client_wrapper/install_selenium_extensions.py, line 16 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEW71F3EdygIqPk2K_d:-KEW71F3EdygIqPk2K_e:-642626597) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9c8b3471a59aa92260fb05c334c3fb1534f49681/client_wrapper/install_selenium_extensions.py#L16)):*
I tested this on Win10 and I get a 403:

```
C:\ndt-e2e-clientworker>\Python27\python.exe client_wrapper\install_selenium_extensions.py --browser=edge
Traceback (most recent call last):
  File "client_wrapper\install_selenium_extensions.py", line 95, in <module>
    main(parser.parse_args())
  File "client_wrapper\install_selenium_extensions.py", line 79, in main
    _download_edge_drivers()
  File "client_wrapper\install_selenium_extensions.py", line 64, in _download_edge_drivers
    urllib.URLopener().retrieve(url, full_edgedriver_path)
  File "C:\Python27\lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 457, in open_https
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "C:\Python27\lib\urllib.py", line 381, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "C:\Python27\lib\urllib.py", line 386, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 403, 'Forbidden', <httplib.HTTPMessage instance at 0x0240D828>)
```

I see the same thing with `wget` on a Linux box:

```
$ wget https://www.microsoft.com/en-us/download/conrmation.aspx?id=48212
--2016-04-04 07:56:00--  https://www.microsoft.com/en-us/download/confirmation.aspx?id=48212
Resolving www.microsoft.com (www.microsoft.com)... 23.72.255.183, 2600:1402:14:293::2768, 2600:1402:14:28e::2768, ...
Connecting to www.microsoft.com (www.microsoft.com)|23.72.255.183|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-04-04 07:56:01 ERROR 403: Forbidden.
```

---

*[client_wrapper/install_selenium_extensions.py, line 28 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEW8JYLMF_zjk_rDSnK:-KEW8JYLMF_zjk_rDSnL:1847541294) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9c8b3471a59aa92260fb05c334c3fb1534f49681/client_wrapper/install_selenium_extensions.py#L28)):*
Can we use the `tempfile` module? The user is not guaranteed to have a `Downloads` folder in their home path. This fails for me on a default Ubuntu install.

---

*[client_wrapper/install_selenium_extensions.py, line 33 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEWCdyuEfPqj6gKlgyX:-KEWCdyuEfPqj6gKlgyY:-1377601676) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9c8b3471a59aa92260fb05c334c3fb1534f49681/client_wrapper/install_selenium_extensions.py#L33)):*
One-line summary should have punctuation:

https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments

Can you rebase onto master? I added an automated linter for docstrings that would have flagged this.

---

*[client_wrapper/install_selenium_extensions.py, line 72 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEWBG7dI9O2-RscoIYs:-KEWBG7dI9O2-RscoIYt:724563246) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9c8b3471a59aa92260fb05c334c3fb1534f49681/client_wrapper/install_selenium_extensions.py#L72)):*
We're repeating this two-line pattern a lot. Can we define a wrapper function for it to reduce the repeated code? Also, if we define the filename as part of the URLs dictionary, it can be reduced to something like:
```
remote_file = driver_urls['safari_os_x']
downloaded_path = download_temp_file(remote_file['url'], remote_file['filename'])
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15)*

**Comment by rowanv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[client_wrapper/install_selenium_extensions.py, line 16 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEW71F3EdygIqPk2K_d:-KEaNGXuBCXi2NphAcFh:2011276472) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9c8b3471a59aa92260fb05c334c3fb1534f49681/client_wrapper/install_selenium_extensions.py#L16)):*
Whoops, wrong URL. Fixed and checked it worked.

---

*[client_wrapper/install_selenium_extensions.py, line 28 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEW8JYLMF_zjk_rDSnK:-KEaL1zZosAf10ggojJl:-1962606206) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9c8b3471a59aa92260fb05c334c3fb1534f49681/client_wrapper/install_selenium_extensions.py#L28)):*
Sounds good, fixed.

---

*[client_wrapper/install_selenium_extensions.py, line 33 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEWCdyuEfPqj6gKlgyX:-KEaFgV3-yVEwDVqm9wd:-2003896356) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9c8b3471a59aa92260fb05c334c3fb1534f49681/client_wrapper/install_selenium_extensions.py#L33)):*
Thanks, fixed.

---

*[client_wrapper/install_selenium_extensions.py, line 72 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEWBG7dI9O2-RscoIYs:-KEaMZzx0cd_IIV5REfH:1250065474) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/9c8b3471a59aa92260fb05c334c3fb1534f49681/client_wrapper/install_selenium_extensions.py#L72)):*
Sounds good, changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15)*

**Comment by mtlynch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client_wrapper/install_selenium_extensions.py, line 28 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEaXIbAT2twwApuUYlI:-KEaXIbAT2twwApuUYlJ:2122081707) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/00f49f125562315501f38d65c7912d20049fbcd1/client_wrapper/install_selenium_extensions.py#L28)):*
Filename should be `MicrosoftWebDriver.msi`.  It's not a zip file.

---

*[client_wrapper/install_selenium_extensions.py, line 43 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEaXW66jaXkonRqyduu:-KEaXW66jaXkonRqyduv:-300182172) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/00f49f125562315501f38d65c7912d20049fbcd1/client_wrapper/install_selenium_extensions.py#L43)):*
These `_download_temp_file` calls are all identical, so we can have a single call outside the `if`/`elif` block.

---

*[client_wrapper/install_selenium_extensions.py, line 44 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEaXUrLoQpCJQD3rzqP:-KEaXUrLoQpCJQD3rzqQ:1462321535) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/00f49f125562315501f38d65c7912d20049fbcd1/client_wrapper/install_selenium_extensions.py#L44)):*
Extraneous newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15)*

**Comment by rowanv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client_wrapper/install_selenium_extensions.py, line 28 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEaXIbAT2twwApuUYlI:-KEb-VRHslKalhzW3fmH:-1001903172) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/00f49f125562315501f38d65c7912d20049fbcd1/client_wrapper/install_selenium_extensions.py#L28)):*
thanks, fixed.

---

*[client_wrapper/install_selenium_extensions.py, line 43 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEaXW66jaXkonRqyduu:-KEb0-o2QEmsXaZuSVr8:-499146009) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/00f49f125562315501f38d65c7912d20049fbcd1/client_wrapper/install_selenium_extensions.py#L43)):*
Done.

---

*[client_wrapper/install_selenium_extensions.py, line 44 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-KEaXUrLoQpCJQD3rzqP:-KEb06R84SfmZf48vO2Z:-499146009) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/00f49f125562315501f38d65c7912d20049fbcd1/client_wrapper/install_selenium_extensions.py#L44)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15)*

**Comment by mtlynch** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/15#-:-KEb2hpOrH9f-e_cUVSp:1417088721)*

**Pull request merged**
