### PR TITLE
Adding docstring checker

### PR DESCRIPTION
**Pull request by mtlynch**
Adding automatic docstring style checking
* Adds automatic docstring style checks to the build script.
* Also fixes a minor docstring error in html5_driver.py.

Looking for validation of the following:
* Third-party code is placed in a reasonable location
* I have done due diligence in attributing third-party code in accordance with the code's license
* It is clear where the third-party code comes from and how to update it
* The whitelisted pylint checks are clear and desirable checks for our team

This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/12)

### CODE REVIEW

**Comment by nkinkade** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[build, line 12 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12#-KEHKvca6yQ2_604lPr3:-KEHKvcbmQWk1FxVrzk-:715165182) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/0e6e2fb151b3f5eafbbd771731f681f33030eca8/build#L12)):*
Using env here is probably fine, but is unnecessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12)*

**Comment by mtlynch** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[build, line 12 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12#-KEHKvca6yQ2_604lPr3:-KEHOt8_fCM9bDiSRhVO:1422717868) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/0e6e2fb151b3f5eafbbd771731f681f33030eca8/build#L12)):*
Fixed, thanks

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12)*

**Comment by nkinkade** [comment]
Reviewed 4 of 7 files at r1, 1 of 1 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[third_party/docstringchecker/LICENSE, line 1 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12#-KEHTPveZGPoV__s4pAp:-KEHTPvf663gBf348ZyC:-933496137) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/395fb76fd31c6b711401451035b9c02b1af81263/third_party/docstringchecker/LICENSE#L1)):*
The copyright notice in lint.py specifies 2013, should this file be consistent with that one?

---

*[third_party/docstringchecker/LICENSE, line 27 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12#-KEHWagiSa3-y9cdD-mL:-KEHWagj239RWs3gkzSz:-2000399043) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/395fb76fd31c6b711401451035b9c02b1af81263/third_party/docstringchecker/LICENSE#L27)):*
Are the javascript-style comment characters necessary at the beginning of each line of a textual license file?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12)*

**Comment by mtlynch** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[third_party/docstringchecker/LICENSE, line 1 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12#-KEHTPveZGPoV__s4pAp:-KEHXfS5RyBOhM3-ZaQG:623899451) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/395fb76fd31c6b711401451035b9c02b1af81263/third_party/docstringchecker/LICENSE#L1)):*
I think we're supposed to just copy the LICENSE as is. LICENSE is direct from here:
https://chromium.googlesource.com/chromiumos/chromite/+/master/LICENSE

---

*[third_party/docstringchecker/LICENSE, line 27 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12#-KEHWagiSa3-y9cdD-mL:-KEHXlYp1yxg8Te7-CMO:1547443968) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/395fb76fd31c6b711401451035b9c02b1af81263/third_party/docstringchecker/LICENSE#L27)):*
Yeah, it's sort of odd, but that's what the original license includes, so I'm keeping it to be faithful to that license file:
https://chromium.googlesource.com/chromiumos/chromite/+/master/LICENSE

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 2 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/12#-:-KEHafpdzxdyOOwllAWk:1417088721)*

**Pull request merged**
