### PR TITLE
Adding support for OS and browser canonicalization

### PR DESCRIPTION
**Pull request by mtlynch**
This adds functionality to canonicalize OS and browser names into common,
canonical formats used in client_wrapper's output filenames.

See the [design doc section](https://docs.google.com/document/d/16b0EesUFrt8eZ1T_f0wPkhC3qkG3W0o8RT4K5_8I9KE/edit#heading=h.khz5pfiy3nt4) on output filenames for additional context.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/9)

### CODE REVIEW

**Comment by nkinkade** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[client_wrapper/canonicalize.py, line 49 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-KE7liBaC7GeziNY3LY_:-KE7liBaC7GeziNY3LYa:1324166399) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/756b49d49cc06ef6807f8d9c01256d28fa77a2ea/client_wrapper/canonicalize.py#L49)):*
Something seems awkward about defining permissible OS and version combinations in this dict rather than in a configuration file or in names.py or similar. Is this the most maintainable place for this?

---

*[client_wrapper/canonicalize.py, line 86 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-KE7lXv0QgaE8arKheSj:-KE7lXv0QgaE8arKheSk:145481647) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/756b49d49cc06ef6807f8d9c01256d28fa77a2ea/client_wrapper/canonicalize.py#L86)):*
Why do we use the 'v' modifier for version in browser names, but not in OS short names?

---

*[client_wrapper/names.py, line 29 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-KE7lIdmv18xQlbPxNUm:-KE7lIdngLmksQ6Xt7B7:-1545616025) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/756b49d49cc06ef6807f8d9c01256d28fa77a2ea/client_wrapper/names.py#L29)):*
What is the longer term purpose of shortening "Windows-10.0" to "win10"?  And why don't we shorten browser/version combinations too, if shortening is generally useful.  As in, if changing "windows10" to "win10" is useful, then why not "firefox_v45" to "fx45" or similar. Not trying to be nitpicky , but trying to understand the value of the shortening for anything.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9)*

**Comment by nkinkade** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[client_wrapper/names.py, line 29 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-KE7lIdmv18xQlbPxNUm:-KE7tzi1t0SaWFWzm60f:-134126598) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/756b49d49cc06ef6807f8d9c01256d28fa77a2ea/client_wrapper/names.py#L29)):*
Following up on my own comment, Michael pointed out to me that the short names are part of the design document.  The reason for their existence is to avoid file names for tests that are excessively long and hard to read, and this makes sense.

---

*[client_wrapper/names.py, line 32 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-KE7uaVOYPWAWTOQaA1A:-KE7uaVPbEuBPzwZ6aBS:-391688293) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/756b49d49cc06ef6807f8d9c01256d28fa77a2ea/client_wrapper/names.py#L32)):*
Could we use [OS X version numbers](https://en.wikipedia.org/wiki/OS_X#Versions) instead of code names to be consistent with Windows and Ubuntu, and for readability, since something like _osx_mountian_lion_ would be lengthy?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9)*

**Comment by nkinkade** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[client_wrapper/canonicalize.py, line 86 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-KE7lXv0QgaE8arKheSj:-KE7vDpnHRPV8ycIrIQT:-1636379904) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/756b49d49cc06ef6807f8d9c01256d28fa77a2ea/client_wrapper/canonicalize.py#L86)):*
If you're not opposed, I think that, for example, _firefox45_ is more concise and just as readable as _firefox_v45_, and this keeps the short naming more in line with how we do it for the OSes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9)*

**Comment by nkinkade** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9)*

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[client_wrapper/canonicalize.py, line 49 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-KE7liBaC7GeziNY3LY_:-KE7yXhML3P5ebFF_Nma:536825305) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/756b49d49cc06ef6807f8d9c01256d28fa77a2ea/client_wrapper/canonicalize.py#L49)):*
I agree it seems weird here. To be clear, this isn't the part of the system that's in charge of determining what platforms are supported, but it needs to make this check because it can't return a sensible result unless it recognizes the platform. In other words, if we ever see `UnsupportedPlatformError` it means we the developers screwed up and didn't check the platform at an earlier stage.

In the interest of an expedient achievement of M1, is it okay with you if I file this as a bug and defer moving it into a config file later?

---

*[client_wrapper/canonicalize.py, line 86 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-KE7lXv0QgaE8arKheSj:-KE7wW0580-CWUbvOff-:2034494094) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/756b49d49cc06ef6807f8d9c01256d28fa77a2ea/client_wrapper/canonicalize.py#L86)):*
Cool, I like this better. Fixed.

---

*[client_wrapper/names.py, line 32 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-KE7uaVOYPWAWTOQaA1A:-KE7w3jMCey_FRqeMzci:-1263047151) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/756b49d49cc06ef6807f8d9c01256d28fa77a2ea/client_wrapper/names.py#L32)):*
Sure, I like that better. Updated the design doc as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/9#-:-KE85wpaJTsQjF6Dw_P7:1417088721)*

**Pull request merged**
