### PR TITLE
Refactoring create_browser function to common module

### PR DESCRIPTION
**Pull request by mtlynch**
Refactoring the create_browser function to a common module for shared
functions among browser-based NDT tests.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-e2e-clientworker/39)

### CODE REVIEW

**Comment by fernandalavalle** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_html5_driver.py, line 21 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39#-KGEQEpCGwmDbngOfU47:-KGEQEpD_iMqU_BcCaQY:-1295000847) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/be90aeb592e6e4c23c2e34b3db7ba7b2e1090c4b/tests/test_html5_driver.py#L21)):*
Kind of confused about why you import webdriver this way. Wouldn't you want to get at this through browser_client_common and the create_browser function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39)*

**Comment by mtlynch** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_html5_driver.py, line 21 \[r1\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39#-KGEQEpCGwmDbngOfU47:-KGETTzvPyYjLeCQmdwZ:-1872916130) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/be90aeb592e6e4c23c2e34b3db7ba7b2e1090c4b/tests/test_html5_driver.py#L21)):*
Good point! I was mocking out a layer too deep. Fixed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39)*

**Comment by fernandalavalle** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_browser_client_common.py, line 19 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39#-KGHu9L_uFIi5tLLi1tQ:-KGHu9L_uFIi5tLLi1tR:-2051830423) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/25f327ff3d49591c738be58e3a08fc2ca007dd62/tests/test_browser_client_common.py#L19)):*
isn't that the same here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39)*

**Comment by mtlynch** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_browser_client_common.py, line 19 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39#-KGHu9L_uFIi5tLLi1tQ:-KGHv64Ob-wDhYyVdwG7:411271435) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/25f327ff3d49591c738be58e3a08fc2ca007dd62/tests/test_browser_client_common.py#L19)):*
In this case, `browser_client_common` has a direct dependency on `selenium.webdriver`. I'm not sure how else we'd test unless we mock it out. Did you have something else in mind?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39)*

**Comment by fernandalavalle** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_browser_client_common.py, line 19 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39#-KGHu9L_uFIi5tLLi1tQ:-KGHxSXKO1aKOopThX1S:-56311675) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/25f327ff3d49591c738be58e3a08fc2ca007dd62/tests/test_browser_client_common.py#L19)):*
but don't we usually mock it out like through the module? I guess I don't see why this is an exception. Like why not: 

@mock.patch.object(browser_client_common.webdriver, 'Firefox')

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39)*

**Comment by mtlynch** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/test_browser_client_common.py, line 19 \[r2\]](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39#-KGHu9L_uFIi5tLLi1tQ:-KGI2Kksr1VL-8-tLQpC:409862805) ([raw file](https://github.com/m-lab/ndt-e2e-clientworker/blob/25f327ff3d49591c738be58e3a08fc2ca007dd62/tests/test_browser_client_common.py#L19)):*
Oh, I see what you're saying. Yeah, that makes sense. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39)*

**Comment by fernandalavalle** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-e2e-clientworker/39#-:-KGI3CfJGFEL0DhPhl_f:1417088721)*

**Pull request merged**
